# netlify.toml

[[redirects]]
  from = "/api/*" # Captura cualquier petici√≥n que empiece con /api/
  to = "https://wsautenticacionside.devida.gob.pe/api/:splat" # Reconstruye la ruta /api/ en el destino
  status = 200
